FROM debian:buster

RUN apt-get update && apt-get -y install \
	wget curl bash php php-cgi php-mysql \
	php-fpm php-pdo php-gd php-cli \
	php-mbstring redis php-redis \
	&& rm -rf /var/lib/apt/lists/*

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
  && chmod +x wp-cli.phar \
  && mv wp-cli.phar /usr/local/bin/wp

COPY ./config/www.conf /etc/php/7.3/fpm/pool.d

COPY ./config/setup.sh /usr/local/bin/

EXPOSE 9000

CMD ["bash", "/usr/local/bin/setup.sh"]