FROM debian:buster

RUN apt-get update && apt-get install -y nginx openssl

RUN mkdir -p /etc/nginx/ssl

RUN openssl req -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
       -out /etc/nginx/ssl/achraf.crt \
       -keyout /etc/nginx/ssl/achraf.key \
       -subj "/CN=acmaghou"

COPY config/default /etc/nginx/sites-available/default

CMD ["nginx", "-g" , "daemon off;"]